#!/bin/bash
#------------------------
# PrintDCP v1.12
#------------------------
# GNU GPLv3
# (c)2018 Jeff Billings
#------------------------

help () {
  echo "printDCP - automates the process of creating DCP drives"
  echo " "
  echo "Usage:   printDCP \"[volume name]\" [source path] [drive device path]"
  echo " "
  echo "  -g --gui   Graphical Interface"
  echo "  -h --help  Operating Instructions"
}
error () {
  echo "(Error) "$1
  exit 1
}
check () {
  if [[ $? -eq 1 ]]; then
    echo "(Cancelled by user)"
    exit 1
  fi
}
finish () {
  echo "(Finished)"
  exit 0
}
ops () {
  volumeLabel=$1
  sourcePath=$2
  drivePath=$3
  echo "Unmounting drive..."
    umount $drivePath
  echo "Creating partition table..."
    mkfs.ext2 -I 128 -F -L $volumeLabel $sourcePath
  echo "Creating mount destination..."
    mkdir /media/$volumeLabel
  echo "Mounting new volume..."
    mount $drivePath /media/$volumeLabel
  echo "Copying DCP to destination (with checksum)..."
    rsync -a --progress --checksum --chmod 755 $sourcePath /media/$volumeLabel
}
gui () {
  IFS=$'\n'
  drive=$(lsblk -I 8 -d -n -p -P --output NAME,MODEL,SIZE |
    awk -F '"' '{print $2"\n"$4"\n"$6}' |
    zenity --list \
    --title "PrintDCP" \
    --width 400 --height 300 \
    --text "Select a drive to <b>erase</b> and prepare:" \
    --column "Device" --column "Model" --column "Size" \
    2>/dev/null )
  check
  name=$(zenity --entry \
    --title "PrintDCP" \
    --text "Enter a drive name:\n(Up to 20 characters)" \
    --entry-text="DCP001" \
    2>/dev/null)
  check
  source=$(zenity --file-selection --directory \
    --title="Choose source DCP folder ..." \
    --filename=$HOME/ \
    2>/dev/null
  )
  check
  ops $name $source $drive & PIPED_PID=$!
  tail -f /dev/null --pid $PIPED_PID | (
    zenity --progress --pulsate \
    --width=300 --height=200 \
    --title="PrintDCP" \
    --text="Copying DCP..." 2>/dev/null || kill $PIPED_PID );
}
if [ "$#" -eq 0 ]; then
  help
fi
while [[ "$#" > 0 ]]; do case $1 in
  -g|--gui)
    gui
    finish
    shift;;
  -h|--help)
    help
    shift;;
  *)
    if [ $# -ne 3 ]; then
      error "Invalid arguments"
    else
      ops $1 $2 $3
      finish
    fi
esac; shift; done
