#!/bin/bash
#------------------------
# PrintDCP
#------------------------
# GNU GPLv3
# (c)2018 Jeff Billings
#------------------------

help () {
  echo "printDCP - automates the process of creating DCP drives"
  echo " "
  echo "Usage:   printDCP [source path] [drive device path]"
  echo " "
  echo "  -g --gui   Graphical Interface"
  echo "  -h --help  Operating Instructions"
}
error () {
  echo "(Error) "$1
  exit 1
}
check () {
  if [[ $? -eq 1 ]]; then
    echo "(Cancelled by user)"
    exit 1
  fi
}
finish () {
  echo "(Finished)"
  exit 0
}
init () {
  drive=$1
  volume="${drive}1"
  echo "Unmounting device..."
    umount -a $drive
  echo "Creating partition..."
    parted -s $drive mklabel msdos
    parted -s $drive mkpart primary 0% 100%
    mkfs -t ext3 -I 128 -m 0 -F $volume
  echo "Mounting volume..."
    sleep 5
    su -c "gio mount -d ${volume}" $SUDO_USER
}
copy () {
  drive=$1
  source=$2
  volume="${drive}1"
  mount=$(lsblk $volume -o MOUNTPOINT -n)
  echo "Copying DCP, performing checksum, setting permissions..."
    sudo -S rsync -a --progress --checksum --chmod 755 $source $mount
}
gui () {
  IFS=$'\n'
  drive=$(lsblk -I 8 -d -n -p -P --output NAME,MODEL,SIZE |
    awk -F '"' '{print $2"\n"$4"\n"$6}' |
    zenity --list \
    --title="PrintDCP" \
    --width=400 --height=300 \
    --text="Select a drive to <b>erase</b> and prepare:" \
    --column="Device" --column="Model" --column="Size" \
    2>/dev/null )
  check
  source=$(zenity --file-selection --directory \
    --title="Choose source DCP folder ..." \
    --filename=$HOME/ \
    2>/dev/null
  )
  check
  init $drive & PIPED_PID=$!
  tail -f /dev/null --pid $PIPED_PID | (
    zenity --progress --pulsate --auto-close \
    --width=300 --height=150 \
    --title="PrintDCP" \
    --text="Initializing drive..." \
    2>/dev/null || kill $PIPED_PID );
  check
  copy $drive $source & PIPED_PID=$!
  tail -f /dev/null --pid $PIPED_PID | (
    zenity --progress --pulsate --auto-close \
    --width=300 --height=150 \
    --title="PrintDCP" \
    --text="Copying DCP..." \
    2>/dev/null || kill $PIPED_PID );
  check
  zenity --info \
    --width=300 --height=150 \
    --title="PrintDCP" \
    --text="Drive preparation finished." \
    2>/dev/null
}
if [ "$#" -eq 0 ]; then
  help
fi
while [ "$#" -gt 0 ]; do case $1 in
  -h|--help)
    help
    shift;;
  -g|--gui)
    gui
    finish
    shift;;
  *)
    if [ $# -ne 3 ]; then
      error "Invalid arguments"
    else
      drive=$1
      source=$2
      init $drive
      copy $drive $source
      finish
    fi
esac; shift; done
