name: print-dcp
version: '0.14'
summary: A script for preparing and copying DCP drives.
description: |
  PrintDCP can be run as a GUI wizard or terminal command and will
  prepare any drive for a Digital Cinema Package (or "DCP").
grade: devel
confinement: devmode

apps:
  print-dcp:
    command: bash $SNAP/opt/print-dcp/bin/print-dcp.sh -g

parts:
  print-dcp:
    source: .
    plugin: dump
    organize:
      print-dcp.sh: opt/print-dcp/bin/print-dcp.sh