name: print-dcp
version: '0.3'
summary: A script for preparing and copying DCP drives.
description: |
  PrintDCP can be run as a GUI wizard or terminal command and will
  prepare any drive for a Digital Cinema Package (or "DCP").
grade: devel
confinement: devmode

apps:
  print-dcp:
    command: /usr/bin/sudo ./print-dcp.sh -g

parts:
  print-dcp:
    plugin: nil
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp print-dcp.sh $SNAPCRAFT_PART_INSTALL/bin/